name: lambda-calculus-interpreter
version: 0.1.0

extra-source-files:
- README.md

default-extensions:
- OverloadedStrings

library:
  source-dirs: src
  dependencies:
  - array
  - base
  - bytestring
  build-tools:
  - alex
  - happy

executables:
  lambda-calculus-interpreter:
    main:                     Main.hs
    source-dirs: src
    dependencies:
    - array
    - base
    - bytestring
    build-tools:
    - alex
    - happy
